// app/utils/facts.ts - Part of the PrepSense mobile app
// Food facts categorized for loading screen rotation
export const foodFacts = [
  { category: 'Green fact', text: 'Eating one plant-based meal a day can save over 200,000 gallons of water a year.' },
  { category: 'Did you know?', text: 'Broccoli stems and leaves are just as edible as the florets—and often thrown away!' },
  { category: 'Smart choice', text: 'Nearly 1/3 of all food produced globally is wasted. Planning meals helps cut this drastically.' },
  { category: 'Ocean tip', text: 'Choosing MSC-certified seafood helps protect marine ecosystems and prevent overfishing.' },
  { category: 'Zero waste tip', text: 'Brown bananas are perfect for smoothies and baking—don\'t toss them!' },
  { category: 'Eco fact', text: 'Buying local and seasonal produce reduces carbon footprint and supports small farmers.' },
  { category: 'Root to tip', text: 'Carrot tops, beet greens, and celery leaves? All edible and packed with nutrients.' },
  { category: 'Pro tip', text: 'Composting food scraps reduces methane emissions and enriches your soil.' },
  { category: 'Did you know?', text: 'Pineapples take up to 2 years to grow to full size.' },
  { category: 'Fun fact', text: 'White chocolate isn\'t technically chocolate—it contains no cocoa solids, just cocoa butter!' },
  { category: 'Truth bomb', text: 'Avocados are berries. But strawberries? They\'re not.' },
  { category: 'Surprise!', text: 'The first pizza delivery was made to King Umberto I of Italy in 1889.' },
  { category: 'Did you know?', text: 'Sliced bread was banned in the U.S. in 1943 to conserve resources during WWII.' },
  { category: 'Carrot trivia', text: 'Carrots used to be purple before the Dutch bred them orange.' },
  { category: 'Fact time', text: 'Honey never spoils. Archaeologists have found pots of it in ancient tombs—still edible.' },
  { category: 'Breakfast lore', text: 'The world\'s largest omelette weighed over 6 tonnes—that\'s more than an elephant!' },
  { category: 'Cold truth', text: 'Ice cream was once considered a luxury fit only for royalty and the elite.' },
  // Provided text facts
  { category: 'Food Waste', text: 'Around one-third of all food produced is lost or wasted, costing the global economy billions annually.' },
  { category: 'Food Waste', text: 'Food waste generates significant greenhouse gas emissions, contributing to climate change.' },
  { category: 'Food Waste', text: 'Wasted food also represents a loss of resources like water and land, impacting sustainability.' },
  { category: 'Environmental Impact', text: 'Food production accounts for a large portion of global greenhouse gas emissions, with meat and dairy having a higher carbon footprint.' },
  { category: 'Environmental Impact', text: 'Agriculture uses a significant portion of the world\'s habitable land and water resources.' },
  { category: 'Environmental Impact', text: 'Unsustainable farming practices can lead to deforestation, soil degradation, and water pollution.' },
  { category: 'Sustainable Food Systems', text: 'Sustainable food systems prioritize food security, environmental protection, and social equity.' },
  { category: 'Sustainable Food Systems', text: 'A sustainable diet can consider the environmental impact of different foods, with plant-based options generally having a lower carbon footprint.' },
  { category: 'Sustainable Food Systems', text: 'Reducing food waste, promoting locally sourced food, and supporting sustainable farming practices are important aspects of a sustainable food system.' },
  { category: 'Sustainable Practices', text: 'Reducing food waste: This can be achieved through proper storage, meal planning, and donation of surplus food.' },
  { category: 'Sustainable Practices', text: 'Supporting sustainable farming practices: This includes organic farming, agroforestry, and precision agriculture.' },
  { category: 'Sustainable Practices', text: 'Adopting a more plant-based diet: This can reduce the environmental impact of food production.' },
  { category: 'Sustainable Practices', text: 'Consuming locally sourced food: This reduces transportation emissions and supports local economies.' },
]; 